# Auto-generated by /Users/alexanderzjs/Desktop/OpenCore-LiveUSB/UDK/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/Users/alexanderzjs/Desktop/OpenCore-LiveUSB/UDK
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/Users/alexanderzjs/Desktop/OpenCore-LiveUSB/UDK/BaseTools
fi
if [ -e /Users/alexanderzjs/Desktop/OpenCore-LiveUSB/UDK/BaseTools/Bin/Darwin-x86_64 ]
then
  if [ ${PATH//Users/alexanderzjs/Desktop/OpenCore-LiveUSB/UDK/BaseTools/Bin/Darwin-x86_64/} == $PATH ]
  then
    export PATH=/Users/alexanderzjs/Desktop/OpenCore-LiveUSB/UDK/BaseTools/Bin/Darwin-x86_64:$PATH
  fi
fi
